server:
  port: 8086

# 防止给予hostname解析的时间过短，而导致报一个warning
spring:
  cloud:
    inetutils:
      timeout-seconds: 10

eureka:
  instance:
    hostname: 119.91.26.135

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://119.91.26.135:8086/eureka/