server:
  port: 8081

spring:
  application:
    name: software-forwardwebservice
  cloud:
    inetutils:
      timeout-seconds: 10

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    instance-id: ForwardService-8081
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://software-eurekaservice:8086/eureka/