server:
  port: 8081

spring:
  application:
    name: software-forwardwebservice
  cloud:
    inetutils:
      timeout-seconds: 10

    gateway:
      # 路由配置
      routes:
        - id: wallet
          uri: lb://software-walletwebservice

          # 转发wallet微服务的请求
          predicates:
            - Path=/wallet/**

        - id: query
          uri: lb://software-querywebservice

          # 转发query微服务的请求
          predicates:
            - Path=/query/**

        - id: order
          uri: lb://software-orderwebservice

          # 转发order微服务的请求
          predicates:
            - Path=/order/**

eureka:
  instance:
    instance-id: ForwardService-8081
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://software-eurekaservice:8086/eureka/