server:
  port: 8083

spring:
  application:
    name: query-service

  cloud:
    inetutils:
      timeout-seconds: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.12.249:3306/hndx05?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: hndx05
    password: hndx05
    hikari:
      # 服务器太烂了 设置超时时间久一点
      connection-timeout: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  instance:
    instance-id: QueryService-8083
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8086/eureka/

# 高德地图配置
amap:
  # 接口地址
  url: https://restapi.amap.com/v3/weather/weatherInfo
  # 开发者ID
  key: 64efc8656b4bc4856e744235a63b95ab
  # base: 实时天气
  # all: 天气预报
  extensions: base